package pl.edu.pwr.abis.domain.enums;

public enum KryteriumPEM {
    CELE_PROJEKTU,
    PRZYWODZTWO,
    LUDZIE,
    ZASOBY,
    PROCESY,
    REZULTATY_DLA_KLIENTA,
    REZULTATY_DLA_CZLONKOW_ZESPOLU_PROJEKTOWEGO,
    REZULTATY_DLA_INNYCH_ZAANGAZOWANYCH_STRON,
    REZULTATY_I_KLUCZOWE_WSKAZNIKI_WYDAJNOSCI_PROJEKTU
}
