package pl.edu.pwr.abis.domain.enums;

public enum PowodPonaglenia {
    NIEDOSTARCZENIE_OCENY_INDYWIDUALNEJ,
    NIEDOSTARCZENIE_OCENY_WSTEPNEJ,
    NIEDOSTARCZENIE_OCENY_KONCOWEJ,
    NIEDOSTARCZENIE_RAPORTU_Z_WIZYTY_STUDYJNEJ
}
